services:
  mysql:
    image: mysql:8.0
    container_name: redesign-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
    ports:
      - "${DB_PORT}:${DB_PORT}"